import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import TagRepo from "@/repos/tag/TagRepository";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const tagGroups = await TagRepo.getTagGroups();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 bg-white">
          <Link href={"/"}>Emily Homepage :)</Link>
          {tagGroups.map((tagGroup, i) => (
            <div key={tagGroup.id + i} className="inline-block">
              <Link href={"/"}>{tagGroup.title}</Link>
              <ul>
                {tagGroup.tags.map((tag, i) => (
                  <li key={`tag-${tag.title}-${i}`}>
                    <Link href={`/tag/${tag.title}`}>{tag.title}</Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
